name: Generate Language Stats
on:
  schedule: # Executa diariamente
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar estatísticas de linguagens
        uses: githubocto/flat@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          template: |
            {
              "languages": [
                {% for language in github.event.repositories[0].languages %}
                  {
                    "name": "{{ language.name }}",
                    "size": {{ language.size }},
                    "color": "{{ language.color }}"
                  }{% if not loop.last %},{% endif %}
                {% endfor %}
              ]
            }
          output_file: language-stats.json

      - name: Fazer upload do JSON como artefato
        uses: actions/upload-artifact@v4
        with:
          name: language-stats
          path: language-stats.json
