name: Generate Language Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:      # Permite execução manual
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... (restante do código do workflow)
